### PR TITLE
Background Changes

### PR DESCRIPTION
**Pull request by dnimitz**
This is a change partially for practice.  I have changed the background
color in the .css document to lavender but I do like it so I will
consider it.

### CODE REVIEW

**Comment by imann24** [comment]
To clarify, do you want me to review and merge pull requests?

**Comment by dnimitz** [comment]
Hello,

I feel like you probably have more important things to do that review pull requests.  I was thinking I might be able to get someone in His Excellency's Chef to help me with that.  Normally I would be happy doing it myself but this is my first website I am making so I would appreciate feedback.  Not necessarily from you because I bet you have a lot going on but I can find someone to do that.  The pull request I sent last night was mostly just to make sure that everything was working so if you want to merge that one to check that you can do that it might be helpful though.  Let me know what you think about that.  I also wanted to say that the recommendation of using the GitHub Desktop was great.  That really helped me figure it out.  I feel like I'm learning a lot here.

Have a good day,

Daniel

**Comment by imann24** [comment]
No problem. Glad to hear it.!Actually, it's no extra trouble for me to approve pull requests. I have to manually update the website each time you push to Git. So I'd be happy to handle the pull requests and provide any feedback / revisions I observe. It's also a part of my responsibilities as GlowLime's Technical Director.

**Comment by dnimitz** [comment]
That is amazing news.  I am happy to know that someone can look at my code so that I will feel more motivated and accountable.  Also it will be nice because this is the first official website I have ever made so feedback is definitely appreciated.

Thank you for that,

Daniel

**Comment by imann24** [comment]
No problem. You're doing excellently thus far!

**Pull request merged**
